[project]
name = "photo-server"
version = "3.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.118.0",
    "uvicorn>=0.34.2",
    "python-multipart>=0.0.27",
    "python-dotenv>=1.2.2",
    "Jinja2>=3.1.6",
    "psycopg[binary,pool]>=3.3.4",
    "virtualenv>=20.36.2",
    "transformers>=5.12.1",
    "pillow>=12.2.0",
    "torch>=2.12.1",
    "torchvision>=0.27.1",
    "pydantic-settings>=2.14.2",
    "setuptools>=83.0.0", # bc of security scan
    "idna>=3.15",
    "openai>=3.13.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pre-commit>=4.5.0",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "ty>=0.0.35",
]

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
torchvision = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.isort]
multi_line_output = 3
include_trailing_comma = true

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
addopts = "--cov=src --cov-report=term-missing"
